module.exports = {
  domain: process.env.MYDOMAIN || "http://localhost:3000",
  coloronlydark: true,
  onlygray: false,
  name: "Khoironi Kurnia Syah",
  image: "/img/me.png",
  profile: "/img/metoo.png",
  thumbnail: "/img/thumbnail.png",
  blogthumbnail: "/img/blog-thumbnail.png",
  role: "Software Engineer",
  description:
    "A software engineer who focus on backend development but also likes user interface. Mathematics student. Indonesian.",
  resume: "https://resume.io/r/iuDuhDJJn",
  socials: [
    { href: "https://github.com/zekhoi", label: "Github" },
    { href: "https://twitter.com/zekhoi", label: "Twitter" },
    {
      href: "https://www.linkedin.com/in/khoironiks",
      label: "Linkedin",
    },
    { href: "https://polywork.com/zekhoi", label: "Polywork" },
  ],
  navlinks: [
    { href: "/", label: "Home" },
    { href: "/about", label: "About" },
    { href: "/blog", label: "Blog" },
    // { href: "/resources", label: "Resources" },
    // { href: "/snippets", label: "Snippets" },
    { href: "/projects", label: "Projects" },
  ],
  about: [
    "Hi! I am Roni. As a mathematics student I like to learn something that can solve problems like web development and machine learning.",
    "On the sidelines of class time I always take the time to write code. I have passionate in backend, but i do frontend when bored. Write code in Javascript, Typescript, Python, PHP for now and Golang in the future.",
    "I have made some projects but i need to improve it and then I can contribute to other. I want to contribute to as many open source projects as possible.",
    "I also want to write at least once a month on Medium so that I can improve my writing and be understood by others.",
  ],
  experiences: [],
  educations: [
    {
      startTime: "August 2022",
      endTime: "Now",
      role: "Fullstack Web Development",
      company: "Synrgy Academy",
      description: "Synrgy Academy Scholarship by BCA x Binar Academy Batch 5",
    },
    {
      startTime: "August 2018",
      endTime: "Now",
      role: "Mathematics",
      company: "Universitas Lambung Mangkurat",
      description: "Take machine learning as a field of study",
    },
  ],
  projects: [
    {
      title: "Coronavirus - Dashboard",
      image: "",
      url: "https://corona.zekhoi.my.id/",
      description: "A website that track corona virus every country.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
    {
      title: "Personal Website - SPA",
      image: "",
      url: "https://zekhoi.my.id/",
      description:
        "My Personal website version 2 build with NextJS and Tailwind.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
    {
      title: "Korobot - Discord Bot",
      image: "",
      url: "https://discord.com/api/oauth2/authorize?client_id=935198224761896980&permissions=8&scope=bot",
      description: "A basic discord bot, it can speak.",
      stacks: ["nodejs", "javascript"],
    },
    {
      title: "Seminar Schedule - Event Calendar",
      image: "",
      url: "https://seminar.zekhoi.my.id/",
      description: "Seminar Schedule Event Calendar from Matematika FMIPA ULM.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
    {
      title: "Booku - Technical Test",
      image: "",
      url: "https://booku.zekhoi.my.id/",
      description: "Technical test result.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
    {
      title: "Alternate Reality - Landing Page",
      image: "",
      url: "https://altrea.id/",
      description:
        "Virtual Group with a focus on developing young talent in the virtual creative industry.",
      stacks: ["tailwindcss", "nextjs", "vercel"],
    },
  ],
  colors: {
    primary: {
      50: "#F0F9FF",
      100: "#DBF1FF",
      200: "#B8E2FF",
      300: "#8AD0FF",
      400: "#52BAFF",
      500: "#0099FF",
      600: "#008AE6",
      700: "#007ACC",
      800: "#0065A8",
      900: "#00497A",
    },
    success: {
      50: "#EEFCF6",
      100: "#DCF9EE",
      200: "#B0F2D8",
      300: "#80EAC0",
      400: "#3FDF9F",
      500: "#22CC88",
      600: "#1FB87A",
      700: "#1BA26C",
      800: "#17875A",
      900: "#106040",
    },
    danger: {
      50: "#FFF5F8",
      100: "#FFE5EE",
      200: "#FFCCDD",
      300: "#FFA8C5",
      400: "#FF7AA7",
      500: "#FF0055",
      600: "#EB004E",
      700: "#CC0044",
      800: "#AD003A",
      900: "#750027",
    },
    warning: {
      50: "#FFF8EB",
      100: "#FFF3DB",
      200: "#FFE4AD",
      300: "#FFD480",
      400: "#FFC247",
      500: "#FFAA00",
      600: "#E69900",
      700: "#CC8800",
      800: "#A87000",
      900: "#7A5200",
    },
  },
};
