/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/no-var-requires */

const { writeFile, existsSync, mkdirSync } = require("fs");
const { join } = require("path");

const path = join(process.cwd(), "data", "_contents");
const today = new Date().toDateString().replace(/\s+/g, "-").toLowerCase();
const template = `---
title: "Starter template"
publishedAt: "${today}"
description: "."
thumbnail: ""
tag: ""
---

# Generated by script
`;

const createNewMDX = (folder) => {
  const path = folder + "/" + today + ".mdx";
  writeFile(path, template, (err) => {
    if (err) throw err;
    console.log("File created successfully at ", path);
  });
};

const main = () => {
  const type = process.argv.slice(2)[0];
  const valid = type !== "blog" || type !== "snippets";

  if (!type && valid)
    return console.log("Please insert an argument (type : blog || snippet)");

  const folder = join(path, type);
  if (!existsSync(folder)) mkdirSync(folder);

  switch (type) {
    case "blog":
      createNewMDX(folder);
      break;
    case "snippets":
      createNewMDX(folder);
      break;
    default:
      console.log("Something went wrong!");
      break;
  }
};

main();
